### PR TITLE
Replace ts() to E::ts()

### PR DESCRIPTION
**Pull request by lucky091588**

### CODE REVIEW

**Comment by lucky091588** [comment]
> @lucky091588
> 
> Hi
> 
> Although work fine, keep getting "Unknown extension key in a translation string: com.joinery.hideactivitytypes" notification.

@tapashdatta I think that error is not related to this extension. I checked it on my local and I don't have that kind of error. Anyway, thanks for commenting on this PR.

**Comment by lucky091588** [comment]
I already check this and there is not E error.

**Comment by tapashdatta** [comment]
Oops!! Wrong repo. Sorry. Will post to current one. Thanks

**Comment by twomice** [comment]
Merged, thanks @lucky091588

**Pull request merged**
